from __future__ import absolute_import, division, print_function

import tflearn
from tflearn.data_utils import shuffle, to_categorical
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.estimator import regression
from tflearn.data_preprocessing import ImagePreprocessing
from tflearn.data_augmentation import ImageAugmentation



# Real-time data preprocessing
img_prep = ImagePreprocessing()
img_prep.add_featurewise_zero_center()
img_prep.add_featurewise_stdnorm()

# Real-time data augmentation
img_aug = ImageAugmentation()
img_aug.add_random_flip_leftright()
img_aug.add_random_rotation(max_angle=25.)

# Convolutional network building
## To Do. same as before.
    ## Define your network here
network = input_data(shape=[None, 100, 100, 3], 
                        data_preprocessing=img_prep, 
                        data_augmentation=img_aug) 

network = conv_2d(network, 64, 3, activation='relu') 
network = max_pool_2d(network, 2) 
network = conv_2d(network, 32, 3, activation='relu')  
network = max_pool_2d(network, 2) 
network = conv_2d(network, 32, 3, activation='relu')  
network = max_pool_2d(network, 2) 
network = fully_connected(network, 256, activation='relu') 
network = dropout(network, 0.5) 
network = fully_connected(network, 256, activation='relu') 
network = dropout(network, 0.5) 
network = fully_connected(network, 10, activation='softmax') 
network = regression(network, optimizer='adam', 
                        loss='categorical_crossentropy', 
                        learning_rate=0.001) 
# Define model
## To Do
    ## Define model and assign network. Same as training.
model = tflearn.DNN(network, tensorboard_verbose=0)
# Load Model into model object
## To Do.
    ## Use the model.load() function
model.load('model/predictdistracted.tfl')

# load test images
from tflearn.data_utils import image_preloader
import numpy as np
# Load path/class_id image file:


data_dir = "imgs/test1/"
#model_path = "vggmodel"
# the file gen by generated by gen_files_list.py
#files_list = "/path/to/your/file/with/images"


#X, Y = image_preloader(files_list, image_shape=(224, 224), mode='file',
 #                      categorical_labels=True, normalize=False,
  #                     files_extension=['.jpg', '.png'], filter_channel=True)
# or use the mode 'floder'
X, Y = image_preloader(data_dir, image_shape=(100, 100), mode='folder',
                        categorical_labels=True, normalize=True,
                        files_extension=['.jpg', '.png'], filter_channel=True)

#from tflearn.data_utils import build_hdf5_image_dataset
#build_hdf5_image_dataset(data_dir, image_shape=(100, 100), mode='folder', output_path='dataset.h5', categorical_labels=True, normalize=True)

# Load HDF5 dataset
#import h5py
#h5f = h5py.File('dataset.h5', 'r')

#X = h5f['X']
#Y = h5f['Y']

X = np.array(X)
Y = np.array(Y)
print('===========================',X.shape)
# predict test images label
y_pred = model.predict(X)

#import pandas as pd
#import os

#names = os.listdir("imgs/test1/0/")
#pd.DataFrame(np.column_stack([names,y_pred]),columns=['img','c0','c1','c2','c3','c4','c5','c6','c7','c8','c9']).to_csv("predict1.csv", index=False)
# Compute accuracy of trained model on test images
print ("Accuracy: ",np.sum(np.argmax(y_pred, axis=1) == np.argmax(Y, axis=1))*100/Y.shape[0],"%")
